0x0C. Web server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -19,9 +19,10 @@ path_to_ssh_key=4
 scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
 # checking if the transfer was succesfful
-if [ $? eq 0 ]
+if [ $? -eq 0 ]
 then
 	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 
-elsei
-	echo "ERROR"
+else
+	echo "AN ERROR ON FILE TRANSFER"
+fi
