0x0C. Web server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -8,7 +8,23 @@
 
 if [ $# -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
-fi
+  	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  	exit 1
+
+# assigning paramentals to the variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabling strict host key checking
+  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
+
+  # checking if the transfer was successful
+if [ s? -eq 0 ]
+then 
+	echo "File was transfered successfully"
+
+else 
+	echo "File transfer has failed"
